version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: gin_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gin-api
      MYSQL_USER: root
    ports:
      - 3306:3306