version: "3.7"

services:
  server:
    build: .
    command: go run main.go
    volumes:
        - .:/go/src/gin-api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gin-api
      MYSQL_USER: root
    ports:
      - 3306:3306