development:
    dialect: mysql
    datasource: root:password@tcp(docker.for.mac.localhost:3306)/gin-api?charset=utf8mb4&parseTime=True&loc=Local
    dir: migrations

production:
    dialect: postgres
    datasource: dbname=myapp sslmode=disable
    dir: migrations/postgres
